name: movie_index
description: Simple movies library app

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: 3.19.0

dependencies:
  auto_route: 8.1.2
  bloc_test: ^9.1.7
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^7.7.0
  hooked_bloc: ^1.5.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  mocktail: ^1.0.4
  retrofit: ^4.2.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter  
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1

flutter:  
  uses-material-design: true
  assets:
    - assets/.tmdb_bearer_token.txt
